disabled_rules: # rule identifiers to exclude from running
  - class_delegate_protocol
  - empty_parentheses_with_trailing_closure
  - force_try
  - force_cast
  - function_parameter_count
  - identifier_name
  - inclusive_language
  - line_length
  - orphaned_doc_comment
  - switch_case_on_newline
  - todo
  - xctfail_message
  - generic_type_name
  - multiple_closures_with_trailing_closure

opt_in_rules: # some rules are only opt-in
  - anyobject_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - comma
  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_object_literal
  - duplicate_enum_cases
  - duplicate_imports
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - explicit_init
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - identical_operands
  - implicit_getter
  - is_disjoint
  - joined_default_parameter
  - last_where
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - literal_expression_end_indentation
  - opening_brace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - shorthand_operator
  - sorted_imports
  - statement_position
  - syntactic_sugar
  - toggle_bool
  - trailing_comma
  - trailing_whitespace
  - type_body_length
  - type_name
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return
  - weak_delegate

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

anyobject_protocol:
  severity: error
closing_brace:
  severity: error
closure_end_indentation:
  severity: error
closure_parameter_position:
  severity: error
comma:
  severity: error
comment_spacing:
  severity: error
compiler_protocol_init:
  severity: error
computed_accessors_order:
  severity: error
contains_over_filter_count:
  severity: error
contains_over_filter_is_empty:
  severity: error
contains_over_first_not_nil:
  severity: error
contains_over_range_nil_comparison:
  severity: error
control_statement:
  severity: error
cyclomatic_complexity:
  ignores_case_statements: true
  warning: 15
discarded_notification_center_observer:
  severity: error
discouraged_direct_init:
  severity: error
discouraged_object_literal:
  severity: error
duplicate_enum_cases:
  severity: error
duplicate_imports:
  severity: error
empty_collection_literal:
  severity: error
empty_count:
  severity: error
empty_enum_arguments:
  severity: error
empty_parameters:
  severity: error
empty_string:
  severity: error
explicit_init:
  severity: error
fatal_error_message:
  severity: error
file_name_no_space:
  severity: error
file_length:
  warning: 750
  error: 750
first_where:
  severity: error
flatmap_over_map_reduce:
  severity: error
for_where:
  severity: error
function_body_length:
  warning: 100
  error: 100
identifier_name:
  severity: error
  excluded:
  - id  # Used in HFDomain -> *Entitiy.swift
  - f   # Used in HFAPI -> AlamofireUtils.swift
identical_operands:
  severity: error
implicit_getter:
  severity: error
is_disjoint:
  severity: error
joined_default_parameter:
  severity: error
large_tuple:
  warning: 5
  error: 5
last_where:
  severity: error
legacy_cggeometry_functions:
  severity: error
legacy_constant:
  severity: error
legacy_constructor:
  severity: error
legacy_hashing:
  severity: error
legacy_multiple:
  severity: error
legacy_nsgeometry_functions:
  severity: error
legacy_random:
  severity: error
literal_expression_end_indentation:
  severity: error
nesting:
  type_level: 3
  severity: error
opening_brace:
  severity: error
overridden_super_call:
  severity: error
prefer_self_type_over_type_of_self:
  severity: error
redundant_discardable_let:
  severity: error
redundant_nil_coalescing:
  severity: error
redundant_objc_attribute:
  severity: error
redundant_optional_initialization:
  severity: error
redundant_set_access_control:
  severity: error
redundant_string_enum_value:
  severity: error
redundant_void_return:
  severity: error
shorthand_operator:
  severity: error
sorted_imports:
  severity: error
statement_position:
  severity: error
syntactic_sugar:
  severity: error
toggle_bool:
  severity: error
trailing_comma:
  severity: error
trailing_whitespace:
  severity: error
type_body_length:
  warning: 400
  error: 400
type_name:
  max_length: 60
  severity: error
  excluded:
  - hf
  - UI
  - ID
  - S
unused_capture_list:
  severity: error
unused_closure_parameter:
  severity: error
unused_control_flow_label:
  severity: error
unused_declaration:
  severity: error
unused_enumerated:
  severity: error
unused_import:
  severity: error
unused_optional_binding:
  severity: error
vertical_parameter_alignment:
  severity: error
vertical_parameter_alignment_on_call:
  severity: error
vertical_whitespace:
  severity: error
vertical_whitespace_closing_braces:
  severity: error
vertical_whitespace_opening_braces:
  severity: error
void_return:
  severity: error
weak_delegate:
  severity: error
